name: Docs

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install autodocsumm
        pip install sphinx_rtd_theme
        pip install sphinx_gallery
        pip install sphinxcontrib-inlinesyntaxhighlight
        pip install sphinx_toolbox
        cd python
        python setup.py develop
        cd ..
        pip install numpy
    - name: Build documents with Sphinx
      run: |
        cd docs
        make html
        cd ..
